# Generated by Django 4.2.6 on 2023-10-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('cidades', '0001_initial'),
        ('alunos', '0003_alter_aluno_cidade_alter_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cidades.cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
            preserve_default=False,
        ),
    ]
